version: "3.3"
services:
  spring-boot-app:
    container_name: spring-app
    image: ipreencekmr/employee
    restart: on-failure
    build: .
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: db.learn-coding.xyz
      MYSQL_USER: root
      MYSQL_PASSWORD: developer
      MYSQL_PORT: 3306
      MYSQL_DATABASE: employee
