version: "3.3"
services:
  spring-boot-app:
    container_name: spring-app
    image: ipreencekmr/employee
    restart: on-failure
    depends_on:
      - mysqldb
    build: .
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: developer
      MYSQL_PORT: 3306
      MYSQL_DATABASE: employee

  mysqldb:
    container_name: mysqldb
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: employee
      MYSQL_ROOT_PASSWORD: developer
