name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Install dependencies
      run: mvn install
      
    - name: Compile and build
      run: mvn compile && mvn package
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ipreencekmr/employee
      
    - name: Docker Login
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Publish Image
      run: docker push ipreencekmr/employee
